from copy import deepcopy

AUTHN_RESPONSE_SPID = {
    "code": "usDwMnEzJPpG5oaV8x3j&",
    "state": "fyZiOL9Lf2CeKuNT2JzxiLRDink0uPcd&",
}

AUTHN_RESPONSE_SPID_NO_CODE = deepcopy(AUTHN_RESPONSE_SPID)
AUTHN_RESPONSE_SPID_NO_CODE.pop("code")

AUTHN_RESPONSE_SPID_NO_STATE = deepcopy(AUTHN_RESPONSE_SPID)
AUTHN_RESPONSE_SPID_NO_STATE.pop("state")

AUTHN_RESPONSE_SPID_NO_CORRECT_STATE = deepcopy(AUTHN_RESPONSE_SPID)
AUTHN_RESPONSE_SPID_NO_CORRECT_STATE["state"] = "tooshort"

AUTHN_RESPONSE_CIE = deepcopy(AUTHN_RESPONSE_SPID)
AUTHN_RESPONSE_CIE["iss"] = "https://idserver.servizicie.interno.gov.it"

AUTHN_RESPONSE_CIE_NO_ISS = deepcopy(AUTHN_RESPONSE_CIE)
AUTHN_RESPONSE_CIE_NO_ISS.pop("iss")

AUTHN_RESPONSE_CIE_NO_CORRECT_ISS = deepcopy(AUTHN_RESPONSE_CIE)
AUTHN_RESPONSE_CIE_NO_CORRECT_ISS["iss"] = ""

AUTHN_ERROR_RESPONSE = {
    "error_description": "request%20malformata&",
    "code": "usDwMnEzJPpG5oaV8x3j&",
    "state": "fyZiOL9Lf2CeKuNT2JzxiLRDink0uPcd&",
}

AUTHN_ERROR_RESPONSE_SPID = deepcopy(AUTHN_ERROR_RESPONSE)
AUTHN_ERROR_RESPONSE_SPID["error"] = "invalid_request"

AUTHN_ERROR_RESPONSE_SPID_NO_CODE = deepcopy(AUTHN_ERROR_RESPONSE)
AUTHN_ERROR_RESPONSE_SPID_NO_CODE.pop("code")

AUTHN_ERROR_RESPONSE_SPID_NO_STATE = deepcopy(AUTHN_ERROR_RESPONSE)
AUTHN_ERROR_RESPONSE_SPID_NO_STATE.pop("state")

AUTHN_ERROR_RESPONSE_SPID_NO_CORRECT_STATE = deepcopy(AUTHN_ERROR_RESPONSE)
AUTHN_ERROR_RESPONSE_SPID_NO_CORRECT_STATE["state"] = "tooshort"

AUTHN_ERROR_RESPONSE_CIE = deepcopy(AUTHN_ERROR_RESPONSE)
AUTHN_ERROR_RESPONSE_CIE["error"] = "unsupported_response_type"
AUTHN_ERROR_RESPONSE_CIE["iss"] = "https://idserver.servizicie.interno.gov.it"

AUTHN_ERROR_RESPONSE_CIE_NO_ISS = deepcopy(AUTHN_ERROR_RESPONSE_CIE)
AUTHN_ERROR_RESPONSE_CIE_NO_ISS.pop("iss")

AUTHN_ERROR_RESPONSE_CIE_NO_CORRECT_ISS = deepcopy(AUTHN_ERROR_RESPONSE_CIE)
AUTHN_ERROR_RESPONSE_CIE_NO_CORRECT_ISS["iss"] = "//idserver.servizicie.interno.gov.it"
