# Generated by Django 4.0.2 on 2022-02-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_relying_party', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OidcAuthenticationRequest',
            new_name='OidcAuthentication',
        ),
        migrations.AlterModelOptions(
            name='oidcauthentication',
            options={'verbose_name': 'Oidc Authentication', 'verbose_name_plural': 'Oidc Authentications'},
        ),
    ]
