# Generated by Django 4.0.2 on 2022-02-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_relying_party', '0002_rename_oidcauthenticationrequest_oidcauthentication_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oidcauthentication',
            options={'verbose_name': 'OIDC Authentication', 'verbose_name_plural': 'OIDC Authentications'},
        ),
    ]
