# Generated by Django 4.0.2 on 2022-03-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_relying_party', '0003_rename_logged_out_oidcauthenticationtoken_revoked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oidcauthenticationtoken',
            old_name='revoked',
            new_name='logged_out',
        ),
        migrations.RemoveField(
            model_name='oidcauthenticationtoken',
            name='refresh_token',
        ),
    ]
