# Generated by Django 4.0.2 on 2022-03-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_relying_party', '0004_rename_revoked_oidcauthenticationtoken_logged_out_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oidcauthenticationtoken',
            old_name='logged_out',
            new_name='revoked',
        ),
        migrations.AddField(
            model_name='oidcauthenticationtoken',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oidcauthentication',
            name='provider_configuration',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
