# Generated by Django 4.0.3 on 2022-04-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_relying_party', '0007_alter_oidcauthentication_provider_jwks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcauthentication',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='oidcauthentication',
            name='provider_jwks',
        ),
    ]
