# Generated by Django 4.0.5 on 2026-02-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_relying_party', '0008_remove_oidcauthentication_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oidcauthenticationtoken',
            name='code',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
