# Generated by Django 4.0.2 on 2022-03-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_relying_party_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relyingpartytest',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spid_cie_oidc_relying_party_test.relyingpartyreport'),
        ),
    ]
