# Generated by Django 4.0.2 on 2022-02-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spid_cie_oidc_authority", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationentityprofile",
            name="trust_mark_template",
            field=models.JSONField(
                default=dict, help_text="trust marks template for this profile"
            ),
        ),
    ]
