# Generated by Django 4.0.2 on 2022-03-28 12:04

from django.db import migrations, models
import spid_cie_oidc.authority.utils


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_authority', '0007_stafftoken_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafftoken',
            name='token',
            field=models.CharField(default=spid_cie_oidc.authority.utils.random_token, help_text='it will be generated automatically.', max_length=255),
        ),
    ]
