# Generated by Django 4.0.5 on 2022-10-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_authority', '0008_alter_stafftoken_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffToken',
        ),
    ]
