# Generated by Django 4.2.1 on 2023-07-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spid_cie_oidc_authority", "0009_delete_stafftoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="federationdescendant",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="if present it overloads the descendants metadata, in the defined parts. This will be applied to the subordinate only.",
            ),
        ),
        migrations.AlterField(
            model_name="federationdescendant",
            name="metadata_policy",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="if present it overloads the DEFAULT policy. This will be applied recursively to all the descendants.",
            ),
        ),
    ]
