# Generated by Django 4.2.1 on 2023-07-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spid_cie_oidc_authority", "0010_federationdescendant_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="federationdescendant",
            name="issue_x509",
            field=models.BooleanField(
                default=False,
                help_text="Issues x509 certificates in the entity statement.",
            ),
        ),
        migrations.AlterField(
            model_name="federationdescendant",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("federation_entity", "federation_entity"),
                    ("openid_relying_party", "openid_relying_party"),
                    ("openid_provider", "openid_provider"),
                    ("oauth_resource", "oauth_resource"),
                    ("wallet_provider", "wallet_provider"),
                    ("wallet_relying_party", "wallet_relying_party"),
                ],
                default="openid_relying_party",
                help_text="OpenID Connect Federation entity type",
                max_length=33,
            ),
        ),
        migrations.AlterField(
            model_name="federationentityprofile",
            name="profile_category",
            field=models.CharField(
                choices=[
                    ("federation_entity", "federation_entity"),
                    ("openid_relying_party", "openid_relying_party"),
                    ("openid_provider", "openid_provider"),
                    ("oauth_resource", "oauth_resource"),
                    ("wallet_provider", "wallet_provider"),
                    ("wallet_relying_party", "wallet_relying_party"),
                ],
                help_text="Profile id. It SHOULD be a URL but feel free to put whatever",
                max_length=64,
            ),
        ),
    ]
