# Generated by Django 4.2.1 on 2023-07-13 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("spid_cie_oidc_authority", "0011_federationdescendant_issue_x509_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="federationdescendant",
            name="issue_x509",
        ),
    ]
