# Generated by Django 4.2.7 on 2023-11-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spid_cie_oidc_authority", "0012_remove_federationdescendant_issue_x509"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationdescendant",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("federation_entity", "federation_entity"),
                    ("openid_relying_party", "openid_relying_party"),
                    ("openid_provider", "openid_provider"),
                    ("openid_credential_issuer", "openid_credential_issuer"),
                    ("oauth_resource", "oauth_resource"),
                    ("wallet_provider", "wallet_provider"),
                    ("wallet_relying_party", "wallet_relying_party"),
                ],
                default="openid_relying_party",
                help_text="OpenID Connect Federation entity type",
                max_length=33,
            ),
        ),
        migrations.AlterField(
            model_name="federationentityprofile",
            name="profile_category",
            field=models.CharField(
                choices=[
                    ("federation_entity", "federation_entity"),
                    ("openid_relying_party", "openid_relying_party"),
                    ("openid_provider", "openid_provider"),
                    ("openid_credential_issuer", "openid_credential_issuer"),
                    ("oauth_resource", "oauth_resource"),
                    ("wallet_provider", "wallet_provider"),
                    ("wallet_relying_party", "wallet_relying_party"),
                ],
                help_text="Profile id. It SHOULD be a URL but feel free to put whatever",
                max_length=64,
            ),
        ),
    ]
