# Generated by Django 4.0.2 on 2022-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='auth_code',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
