# Generated by Django 4.0.2 on 2022-03-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_provider', '0002_oidcsession_auth_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oidcsession',
            old_name='userinfo_claims',
            new_name='user_claims',
        ),
    ]
