# Generated by Django 4.0.2 on 2022-03-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_provider', '0003_rename_userinfo_claims_oidcsession_user_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='nonce',
            field=models.CharField(default=87346128746127846127846127846238746238742394621389742, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='oidcsession',
            unique_together={('client_id', 'nonce')},
        ),
    ]
