# Generated by Django 4.0.2 on 2022-03-02 11:48

from django.db import migrations, models

import random
import string
import uuid


def get_random_string(length=256):
    # choose from all lowercase letter
    letters = string.ascii_lowercase
    result_str = ''.join(random.choice(letters) for i in range(length))
    res = f"{uuid.uuid4()}{result_str}"
    print(res)
    return res

class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_provider', '0003_rename_userinfo_claims_oidcsession_user_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='nonce',
            field=models.CharField(default=get_random_string, max_length=2048),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='oidcsession',
            unique_together={('client_id', 'nonce')},
        ),
    ]
