# Generated by Django 4.0.2 on 2022-03-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_provider', '0004_alter_oidcsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='sid',
            field=models.CharField(blank=True, help_text='django session key', max_length=1024, null=True),
        ),
    ]
