# Generated by Django 4.0.2 on 2022-03-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_provider', '0005_oidcsession_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcsession',
            name='acr',
            field=models.CharField(default='https://www.spid.gov.it/SpidL2', max_length=1024),
            preserve_default=False,
        ),
    ]
