# Generated by Django 4.2.3 on 2023-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "spid_cie_oidc_provider",
            "0007_alter_issuedtoken_options_alter_oidcsession_options",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="oidcsession",
            name="authz_request",
            field=models.JSONField(max_length=65536),
        ),
    ]
