from copy import deepcopy

REVOCATION_RESPONSE_CIE = {
    "error": "unauthorized_client",
    "error_description": "description of the error",
}

REVOCATION_RESPONSE_CIE_NO_ERROR = deepcopy(REVOCATION_RESPONSE_CIE)
REVOCATION_RESPONSE_CIE_NO_ERROR.pop("error")

REVOCATION_RESPONSE_CIE_NO_CORRECT_ERROR = deepcopy(REVOCATION_RESPONSE_CIE)
REVOCATION_RESPONSE_CIE_NO_CORRECT_ERROR["error"] = []

REVOCATION_RESPONSE_CIE_NO_ERROR_DESCRIPTION = deepcopy(REVOCATION_RESPONSE_CIE)
REVOCATION_RESPONSE_CIE_NO_ERROR_DESCRIPTION.pop("error_description")

REVOCATION_RESPONSE_CIE_NO_CORRECT_ERROR_DESCRIPTION = deepcopy(REVOCATION_RESPONSE_CIE)
REVOCATION_RESPONSE_CIE_NO_CORRECT_ERROR_DESCRIPTION["error_description"] = [
    "error description"
]
