# Generated by Django 4.0.2 on 2022-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnBoardingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(help_text='Organization Name. ', max_length=33)),
                ('url_entity', models.URLField(help_text='URL of the Entity.', max_length=255, unique=True)),
                ('authn_buttons_page_url', models.URLField(help_text='URL of the page where the SPID/CIE button is available.', max_length=255, unique=True)),
                ('public_jwks', models.JSONField(default=dict, help_text='Public jwks of the Entities')),
            ],
        ),
    ]
