# Generated by Django 4.0.2 on 2022-02-05 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationDescendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sub', models.URLField(help_text='URL that identifies this Entity in the Federation.', max_length=255, unique=True)),
                ('type', models.CharField(blank=True, choices=[('openid_relying_party', 'openid_relying_party'), ('openid_provider', 'openid_provider'), ('federation_entity', 'federation_entity'), ('oauth_resource', 'oauth_resource')], default='openid_relying_party', max_length=33)),
                ('jwks', models.JSONField(help_text='a list of public keys')),
                ('trust_marks', models.JSONField(blank=True, default=list, help_text='trust marks released for this subject')),
                ('metadata_policy', models.JSONField(blank=True, default=dict, help_text='if present overloads the DEFAULT policy')),
                ('constraints', models.JSONField(blank=True, default=dict, help_text='if present overloads the DEFAULT policy')),
                ('extended_claims', models.JSONField(blank=True, default=dict, help_text='a dictionary containing any other claim like: jti, crti, policy_language_crit and any other extension')),
                ('registrant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Federation Entity Descendant',
                'verbose_name_plural': 'Federation Entity Descendant',
            },
        ),
    ]
