# Generated by Django 4.0.2 on 2022-02-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationdescendant',
            name='is_active',
            field=models.BooleanField(default=False, help_text='If this entity is active. '),
        ),
    ]
