# Generated by Django 4.0.2 on 2022-02-23 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("spid_cie_oidc_onboarding", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onboardingregistration",
            options={
                "ordering": ["created"],
                "verbose_name": "OnBoarding Registration",
                "verbose_name_plural": "OnBoarding Registrations",
            },
        ),
        migrations.AddField(
            model_name="onboardingregistration",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="onboardingregistration",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
