# Generated by Django 4.0.2 on 2022-02-05 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spid_cie_oidc_onboarding', '0002_federationdescendant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationdescendant',
            name='status',
            field=models.CharField(choices=[(False, False), (True, True), (False, False), (None, None)], default=False, help_text='Its entity configuration is periodically fetched and validated.', max_length=33),
        ),
        migrations.AlterField(
            model_name='federationdescendant',
            name='registrant',
            field=models.ForeignKey(blank=True, help_text='the user who created this entity', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='federationdescendant',
            name='type',
            field=models.CharField(blank=True, choices=[('openid_relying_party', 'openid_relying_party'), ('openid_provider', 'openid_provider'), ('federation_entity', 'federation_entity'), ('oauth_resource', 'oauth_resource')], default='openid_relying_party', help_text='OpenID Connect Federation entity type', max_length=33),
        ),
    ]
