# Generated by Django 4.0.2 on 2022-03-11 13:16

from django.db import migrations, models
import spid_cie_oidc.entity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0003_alter_onboardingregistration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingregistration',
            name='public_jwks',
            field=models.JSONField(default=list, help_text='Public jwks of the Entities', validators=[spid_cie_oidc.entity.validators.validate_public_jwks]),
        ),
    ]
