# Generated by Django 4.0.2 on 2022-02-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0003_federationdescendant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationdescendant',
            name='status_log',
            field=models.JSONField(blank=True, default=dict, help_text='status log'),
        ),
        migrations.AlterField(
            model_name='federationdescendant',
            name='status',
            field=models.CharField(choices=[('unreachable', 'unreachable'), ('valid', 'valid'), ('signature_failed', 'signature_failed'), ('not_valid', 'not_valid'), ('unknown', 'unknown')], default=False, help_text='Its entity configuration is periodically fetched and validated.', max_length=33),
        ),
    ]
