# Generated by Django 4.0.2 on 2022-03-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0004_alter_onboardingregistration_public_jwks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingregistration',
            name='status',
            field=models.CharField(choices=[('onboarded', 'onboarded'), ('failed', 'failed'), ('processing', 'processing'), ('acquired', 'acquired')], default='acquired', max_length=33),
        ),
    ]
