# Generated by Django 4.0.2 on 2022-02-05 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spid_cie_oidc_onboarding', '0004_federationdescendant_status_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationdescendant',
            name='jwks',
            field=models.JSONField(default=list, help_text='a list of public keys'),
        ),
        migrations.RemoveField(
            model_name='federationdescendant',
            name='registrant',
        ),
        migrations.AddField(
            model_name='federationdescendant',
            name='registrant',
            field=models.ManyToManyField(help_text='users that can login and modify sub, contacts and jwks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FederationDescendantContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact', models.CharField(help_text='any kind of contact type, usually an email.', max_length=255)),
                ('type', models.CharField(choices=[('email', 'email'), ('telephone', 'telephone'), ('other', 'other')], max_length=255)),
                ('entity', models.ForeignKey(help_text='Entity for which this contac is related', on_delete=django.db.models.deletion.CASCADE, to='spid_cie_oidc_onboarding.federationdescendant')),
            ],
            options={
                'verbose_name': 'Federation Entity Contact',
                'verbose_name_plural': 'Federation Entity Contact',
            },
        ),
    ]
