# Generated by Django 4.0.2 on 2022-03-22 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0006_onboardingregistration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingregistration',
            name='contact',
            field=models.CharField(default=datetime.date(2022, 3, 22), help_text='any kind of contact type, usually an email.', max_length=255),
            preserve_default=False,
        ),
    ]
