# Generated by Django 4.0.2 on 2022-02-06 01:39

from django.conf import settings
from django.db import migrations, models
import spid_cie_oidc.onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spid_cie_oidc_onboarding', '0006_alter_federationdescendant_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationdescendant',
            name='uid',
            field=models.CharField(default=spid_cie_oidc.onboarding.models.FederationDescendant.def_uid, help_text='an unique code that identifies this entry. For italian public service it may be the IPA code.', max_length=33, unique=True),
        ),
        migrations.AlterField(
            model_name='federationdescendant',
            name='registrant',
            field=models.ManyToManyField(help_text="Logged in users can modify only sub, contacts and jwks attributes, if they're owner of this entry. ", to=settings.AUTH_USER_MODEL),
        ),
    ]
