# Generated by Django 4.0.2 on 2022-02-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0007_federationdescendant_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationdescendant',
            name='name',
            field=models.CharField(default='', help_text='human readable name of this entity. It may be a unit or organization name', max_length=33),
            preserve_default=False,
        ),
    ]
