# Generated by Django 4.0.3 on 2022-03-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0007_onboardingregistration_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingregistration',
            name='auth_request_url',
            field=models.CharField(blank=True, help_text='SPID/CIE authentication request trigger url.', max_length=254, null=True),
        ),
    ]
