# Generated by Django 4.0.2 on 2022-02-06 18:00

from django.conf import settings
from django.db import migrations, models
import spid_cie_oidc.onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spid_cie_oidc_onboarding', '0008_federationdescendant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationdescendant',
            name='registrant',
            field=models.ManyToManyField(blank=True, help_text="Logged in users can modify only sub, contacts and jwks attributes, if they're owner of this entry. ", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='federationdescendant',
            name='status',
            field=models.CharField(choices=[('unreachable', 'unreachable'), ('valid', 'valid'), ('signature_failed', 'signature_failed'), ('not_valid', 'not_valid'), ('unknown', 'unknown'), ('expired', 'expired')], default=False, help_text='Its entity configuration is periodically fetched and validated.', max_length=33),
        ),
        migrations.AlterField(
            model_name='federationdescendant',
            name='uid',
            field=models.CharField(default=spid_cie_oidc.onboarding.models.FederationDescendant.def_uid, help_text='an unique code that identifies this entry. For italian public service it may be the IPA code.', max_length=1024, unique=True),
        ),
    ]
