# Generated by Django 4.0.2 on 2022-02-10 17:24

from django.db import migrations, models
import spid_cie_oidc.onboarding.models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0009_alter_federationdescendant_registrant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationEntityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Profile name. ', max_length=33)),
                ('profile_id', models.CharField(help_text='Profile id. It SHOULD be a URL but feel free to put whatever', max_length=1024, unique=True)),
                ('trust_mark_template', models.JSONField(blank=True, default=dict, help_text='trust marks template for this profile')),
            ],
            options={
                'verbose_name': 'Federation Entity Contact',
                'verbose_name_plural': 'Federation Entity Contacts',
            },
        ),
        migrations.AlterField(
            model_name='federationdescendant',
            name='sub',
            field=models.URLField(help_text='URL that identifies this Entity in the Federation.', max_length=255, unique=True, validators=[spid_cie_oidc.onboarding.models.FederationDescendant.validate_entity_configuration]),
        ),
        migrations.AlterField(
            model_name='federationdescendant',
            name='type',
            field=models.CharField(blank=True, choices=[('federation_entity', 'federation_entity'), ('openid_relying_party', 'openid_relying_party'), ('openid_provider', 'openid_provider'), ('oauth_resource', 'oauth_resource')], default='openid_relying_party', help_text='OpenID Connect Federation entity type', max_length=33),
        ),
        migrations.AddField(
            model_name='federationdescendant',
            name='profiles',
            field=models.ManyToManyField(blank=True, help_text='Active profiles for this entity. Defined by QaD test and optionally editable by staff. ', to='spid_cie_oidc_onboarding.FederationEntityProfile'),
        ),
    ]
