# Generated by Django 4.0.2 on 2022-02-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0010_federationentityprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationEntityAssignedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descendant', models.ManyToManyField(to='spid_cie_oidc_onboarding.FederationDescendant')),
                ('profile', models.ManyToManyField(to='spid_cie_oidc_onboarding.FederationEntityProfile')),
            ],
            options={
                'verbose_name': 'Federation Entity Assigned Profile',
                'verbose_name_plural': 'Federation Assigned Profiles',
            },
        ),
        migrations.AlterField(
            model_name='federationdescendant',
            name='profiles',
            field=models.ManyToManyField(blank=True, help_text='Active profiles for this entity. Defined by QaD test and optionally editable by staff. ', to='spid_cie_oidc_onboarding.FederationEntityAssignedProfile'),
        ),
    ]
