# Generated by Django 4.0.2 on 2022-02-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0011_federationentityassignedprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='federationentityprofile',
            options={'verbose_name': 'Federation Entity Profile', 'verbose_name_plural': 'Federation Entity Profiles'},
        ),
        migrations.RemoveField(
            model_name='federationentityassignedprofile',
            name='descendant',
        ),
        migrations.AddField(
            model_name='federationentityassignedprofile',
            name='descendant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spid_cie_oidc_onboarding.federationdescendant'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='federationentityassignedprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='federationentityassignedprofile',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spid_cie_oidc_onboarding.federationentityprofile'),
            preserve_default=False,
        ),
    ]
