# Generated by Django 4.0.2 on 2022-02-10 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0012_alter_federationentityprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federationdescendant',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='federationdescendant',
            name='trust_marks',
        ),
    ]
