# Generated by Django 4.0.2 on 2022-02-11 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_entity', '0008_alter_federationentityconfiguration_metadata_and_more'),
        ('spid_cie_oidc_onboarding', '0013_remove_federationdescendant_profiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationentityassignedprofile',
            name='issuer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spid_cie_oidc_entity.federationentityconfiguration'),
            preserve_default=False,
        ),
    ]
