# Generated by Django 4.0.2 on 2022-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0014_federationentityassignedprofile_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationentityprofile',
            name='profile_category',
            field=models.CharField(choices=[('federation_entity', 'federation_entity'), ('openid_relying_party', 'openid_relying_party'), ('openid_provider', 'openid_provider'), ('oauth_resource', 'oauth_resource')], default='openid_relying_party', help_text='Profile id. It SHOULD be a URL but feel free to put whatever', max_length=1024),
            preserve_default=False,
        ),
    ]
