# Generated by Django 4.0.2 on 2022-02-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0015_federationentityprofile_profile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationentityprofile',
            name='profile_category',
            field=models.CharField(choices=[('federation_entity', 'federation_entity'), ('openid_relying_party', 'openid_relying_party'), ('openid_provider', 'openid_provider'), ('oauth_resource', 'oauth_resource')], help_text='Profile id. It SHOULD be a URL but feel free to put whatever', max_length=64),
        ),
    ]
