# Generated by Django 4.0.2 on 2022-02-12 17:18

from django.db import migrations, models
import spid_cie_oidc.entity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0016_alter_federationentityprofile_profile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationdescendant',
            name='jwks',
            field=models.JSONField(default=list, help_text='a list of public keys', validators=[spid_cie_oidc.entity.validators.validate_public_jwks]),
        ),
    ]
