# Generated by Django 4.0.2 on 2022-02-12 17:45

from django.db import migrations, models
import django.db.models.deletion
import spid_cie_oidc.entity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0017_alter_federationdescendant_jwks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jwk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('kid', models.CharField(help_text='unique code that identifies this jwks. ', max_length=1024, unique=True)),
                ('jwks', models.JSONField(default=dict, help_text='Public jwk', validators=[spid_cie_oidc.entity.validators.validate_public_jwks])),
            ],
            options={
                'verbose_name': 'Federation Entity JWKs',
                'verbose_name_plural': 'Federation Entity JWKs',
            },
        ),
        migrations.RemoveField(
            model_name='federationdescendant',
            name='jwks',
        ),
        migrations.CreateModel(
            name='FederationDescendantJwk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('descendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spid_cie_oidc_onboarding.federationdescendant')),
                ('jwk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spid_cie_oidc_onboarding.jwk')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
