# Generated by Django 4.0.2 on 2022-02-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_onboarding', '0018_jwk_remove_federationdescendant_jwks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jwk',
            old_name='jwks',
            new_name='jwk',
        ),
    ]
