# Generated by Django 4.0.2 on 2022-02-04 23:25

from django.db import migrations, models
import spid_cie_oidc_authority.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederationAuthorityConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sub', models.URLField(help_text='URL that identifies this Entity in the Federation. This value and iss are the same in the Entity Configuration.', max_length=255)),
                ('default_exp', models.PositiveIntegerField(default=33, help_text='how many minutes from now() an issued statement must expire')),
                ('default_signature_alg', models.CharField(default='RS256', help_text='default signature algorithm, eg: RS256', max_length=16)),
                ('authority_hints', models.JSONField(blank=True, default=list, help_text='only required if this Entity is an intermediary')),
                ('jwks', models.JSONField(default=spid_cie_oidc_authority.models.FederationAuthorityConfiguration._create_jwks, help_text='a list of public keys')),
                ('trust_marks', models.JSONField(default=list, help_text='which trust marks MUST be exposed in its entity configuration')),
                ('federation_entity_metadata', models.JSONField(default=dict, help_text='federation_entity metadata')),
                ('watchdog_check_interval', models.PositiveIntegerField(default=5, help_text='Acsia agent will check watchdog commands and execute ephemeral with this timeout.')),
                ('http_timeout', models.PositiveIntegerField(default=5, help_text='in seconds')),
                ('verify_https_cert', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False, help_text='If this configuration is active. At least one configuration must be active')),
            ],
            options={
                'verbose_name': 'Federation Authority Configuration',
                'verbose_name_plural': 'Federation Authority Configurations',
            },
        ),
    ]
