# Generated by Django 4.0.2 on 2022-02-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_authority', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationauthorityconfiguration',
            name='trust_marks',
            field=models.JSONField(blank=True, default=list, help_text='which trust marks MUST be exposed in its entity configuration'),
        ),
    ]
