# Generated by Django 4.0.2 on 2022-02-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_authority', '0002_alter_federationauthorityconfiguration_trust_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='federationauthorityconfiguration',
            name='trust_marks_issuers',
            field=models.JSONField(blank=True, default=dict, help_text='which issuers are allowed to issue trust marks for the descendants. Example: {"https://www.spid.gov.it/certification/rp": ["https://registry.spid.agid.gov.it", "https://intermediary.spid.it"],"https://sgd.aa.it/onboarding": ["https://sgd.aa.it", ]}'),
        ),
    ]
