# Generated by Django 4.0.2 on 2022-02-05 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_authority', '0003_federationauthorityconfiguration_trust_marks_issuers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federationauthorityconfiguration',
            name='watchdog_check_interval',
        ),
    ]
