# Generated by Django 4.0.2 on 2022-02-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_entity', '0002_rename_entity_metadatas_federationentityconfiguration_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sub', models.URLField(help_text='URL that identifies this Entity in the Federation. ', max_length=255)),
                ('type', models.CharField(blank=True, choices=[('openid_relying_party', 'openid_relying_party'), ('openid_provider', 'openid_provider'), ('federation_entity', 'federation_entity'), ('oauth_resource', 'oauth_resource')], default='openid_relying_party', help_text='OpenID Connect Federation entity type', max_length=33)),
                ('exp', models.DateTimeField()),
                ('iat', models.DateTimeField()),
                ('chain', models.JSONField(blank=True, default=list, help_text='A list of entity statements collected during the metadata discovery')),
                ('resultant_metadata', models.JSONField(default=dict, help_text='The final metadata applied with the metadata policy built over the chain')),
                ('parties_involved', models.JSONField(blank=True, default=list, help_text='subjects involved in the metadata discovery')),
                ('status', models.CharField(choices=[('unreachable', 'unreachable'), ('valid', 'valid'), ('signature_failed', 'signature_failed'), ('not_valid', 'not_valid'), ('unknown', 'unknown'), ('expired', 'expired')], default=False, help_text='Status of this trust chain, on each update.', max_length=33)),
                ('status_log', models.JSONField(blank=True, default=dict, help_text='status log')),
                ('is_active', models.BooleanField(default=True, help_text='If you need to disable the trust to this subject, deacticate this')),
            ],
            options={
                'verbose_name': 'Federation Entity Configuration',
                'verbose_name_plural': 'Federation Entity Configurations',
                'unique_together': {('sub', 'type')},
            },
        ),
    ]
