# Generated by Django 4.0.2 on 2022-02-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_entity', '0006_alter_federationentityconfiguration_trust_marks_issuers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federationentityconfiguration',
            name='http_timeout',
        ),
        migrations.RemoveField(
            model_name='federationentityconfiguration',
            name='verify_https_cert',
        ),
    ]
