# Generated by Django 4.0.2 on 2022-02-10 17:24

from django.db import migrations, models
import spid_cie_oidc.entity.models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_entity', '0007_remove_federationentityconfiguration_http_timeout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationentityconfiguration',
            name='metadata',
            field=models.JSONField(default=dict, help_text='federation_entity metadata, eg: {"federation_entity": { ... },"openid_provider": { ... },"openid_relying_party": { ... },"oauth_resource": { ... }}', validators=[spid_cie_oidc.entity.models.FederationEntityConfiguration.validate_entity_metadata]),
        ),
        migrations.AlterField(
            model_name='trustchain',
            name='type',
            field=models.CharField(blank=True, choices=[('federation_entity', 'federation_entity'), ('openid_relying_party', 'openid_relying_party'), ('openid_provider', 'openid_provider'), ('oauth_resource', 'oauth_resource')], default='openid_provider', help_text='OpenID Connect Federation entity type', max_length=33),
        ),
    ]
