# Generated by Django 4.0.2 on 2022-03-13 00:41

from django.db import migrations, models
import spid_cie_oidc.entity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_entity', '0012_delete_publicjwk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationentityconfiguration',
            name='metadata',
            field=models.JSONField(default=dict, help_text='federation_entity metadata, eg: {"federation_entity": { ... },"openid_provider": { ... },"openid_relying_party": { ... },"oauth_resource": { ... }}', validators=[spid_cie_oidc.entity.validators.validate_entity_metadata, spid_cie_oidc.entity.validators.validate_metadata_algs]),
        ),
    ]
