# Generated by Django 4.0.3 on 2022-03-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_entity', '0013_alter_federationentityconfiguration_metadata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trustchain',
            unique_together={('sub', 'trust_anchor')},
        ),
        migrations.RemoveField(
            model_name='trustchain',
            name='type',
        ),
    ]
