# Generated by Django 4.0.3 on 2022-03-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_entity', '0014_alter_trustchain_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trustchain',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='trustchain',
            name='type',
            field=models.CharField(blank=True, choices=[('federation_entity', 'federation_entity'), ('openid_relying_party', 'openid_relying_party'), ('openid_provider', 'openid_provider'), ('oauth_resource', 'oauth_resource')], default='openid_provider', help_text='OpenID Connect Federation entity type', max_length=33),
        ),
        migrations.AlterUniqueTogether(
            name='trustchain',
            unique_together={('sub', 'type', 'trust_anchor')},
        ),
    ]
