# Generated by Django 4.0.3 on 2022-04-23 14:48

from django.db import migrations, models
import spid_cie_oidc.entity.models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_cie_oidc_entity', '0016_alter_trustchain_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='federationentityconfiguration',
            name='jwks',
        ),
        migrations.AddField(
            model_name='federationentityconfiguration',
            name='jwks_core',
            field=models.JSONField(default=spid_cie_oidc.entity.models.FederationEntityConfiguration._create_jwks, help_text='a list of private keys for Core ops'),
        ),
        migrations.AddField(
            model_name='federationentityconfiguration',
            name='jwks_fed',
            field=models.JSONField(default=spid_cie_oidc.entity.models.FederationEntityConfiguration._create_jwks, help_text='a list of private keys for Federation ops'),
        ),
    ]
