# Generated by Django 4.2.1 on 2023-07-08 11:35

from django.db import migrations, models
import spid_cie_oidc.entity.models
import spid_cie_oidc.entity.validators


class Migration(migrations.Migration):
    dependencies = [
        ("spid_cie_oidc_entity", "0019_stafftoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationentityconfiguration",
            name="jwks_core",
            field=models.JSONField(
                blank=True,
                default=spid_cie_oidc.entity.models.FederationEntityConfiguration._create_jwks,
                help_text="a list of private keys for Core ops",
                validators=[spid_cie_oidc.entity.validators.validate_private_jwks],
            ),
        ),
        migrations.AlterField(
            model_name="federationentityconfiguration",
            name="jwks_fed",
            field=models.JSONField(
                default=spid_cie_oidc.entity.models.FederationEntityConfiguration._create_jwks,
                help_text="a list of private keys for Federation ops",
                validators=[spid_cie_oidc.entity.validators.validate_private_jwks],
            ),
        ),
    ]
