# Generated by Django 4.2.1 on 2023-07-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spid_cie_oidc_entity", "0021_federationhistoricalkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="federationhistoricalkey",
            name="jwk",
            field=models.TextField(default={}, help_text="private jwk"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="federationhistoricalkey",
            name="kid",
            field=models.CharField(max_length=33),
        ),
    ]
