# Generated by Django 4.2.1 on 2023-07-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spid_cie_oidc_entity", "0022_federationhistoricalkey_jwk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationhistoricalkey",
            name="jwk",
            field=models.TextField(default={}, help_text="private jwk"),
        ),
    ]
