# Generated by Django 4.2.1 on 2023-07-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spid_cie_oidc_entity", "0024_alter_federationhistoricalkey_kid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationhistoricalkey",
            name="jwk",
            field=models.JSONField(default={}, help_text="private jwk"),
        ),
    ]
