# Generated by Django 4.2.1 on 2023-07-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spid_cie_oidc_entity", "0025_alter_federationhistoricalkey_jwk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationhistoricalkey",
            name="jwk",
            field=models.JSONField(default=dict, help_text="private jwk"),
        ),
    ]
