# Generated by Django 4.2.1 on 2023-07-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "spid_cie_oidc_entity",
            "0021_federationhistoricalkey_squashed_0026_alter_federationhistoricalkey_jwk",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationhistoricalkey",
            name="revocation_motivation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "unspecified"),
                    ("1", "keyCompromise"),
                    ("2", "cACompromise"),
                    ("3", "affiliationChanged"),
                    ("4", "superseded"),
                    ("5", "cessationOfOperation"),
                    ("6", "certificateHold"),
                    ("8", "removeFromCRL"),
                    ("9", "privilegeWithdrawn"),
                    ("10", "aACompromise"),
                ],
                max_length=33,
            ),
        ),
    ]
