# Generated by Django 4.2.7 on 2023-11-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "spid_cie_oidc_entity",
            "0030_remove_federationentityconfiguration_issue_x509",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="federationentityconfiguration",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("federation_entity", "federation_entity"),
                    ("openid_relying_party", "openid_relying_party"),
                    ("openid_provider", "openid_provider"),
                    ("openid_credential_issuer", "openid_credential_issuer"),
                    ("oauth_resource", "oauth_resource"),
                    ("wallet_provider", "wallet_provider"),
                    ("wallet_relying_party", "wallet_relying_party"),
                ],
                default="openid_relying_party",
                help_text="OpenID Connect Federation entity type",
                max_length=33,
            ),
        ),
    ]
