# Generated by Django 4.2.3 on 2023-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "spid_cie_oidc_entity",
            "0031_alter_federationentityconfiguration_entity_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="fetchedentitystatement",
            name="jwt",
            field=models.TextField(blank=False, null=False),
        ),
    ]
